import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe,expect,it,vi } from 'vitest';
import { ExternalEgressControl,MAX_EXECUTABLE_BYTES } from '../provider-routing/ollama-preflight/contracts';
import { ModelAcquisitionControl,PROVIDER_GENERATION_VALIDATION_CONTRACT_VERSION,VALIDATION_PROMPT_DIGEST } from './provider-generation-validation';
import { executeProviderGenerationExecution,parseProviderGenerationExecutionInvocation,PROVIDER_GENERATION_EXECUTION_PROJECTION_KEYS } from './provider-generation-execution';
const hash=createHash('sha256').update('x').digest('hex');
const flags=['--executable-realpath','--expected-executable-sha256','--expected-executable-size-bytes','--approved-loopback-endpoint','--model-acquisition-control','--external-egress-control'];
const values=['/x/ollama',hash,'1','http://127.0.0.1:11434',ModelAcquisitionControl.PRECHECK_OBSERVE_POSTCHECK_RISK_ACCEPTED,ExternalEgressControl.CONFIG_RESTRICTED_RISK_ACCEPTED];
const invocation=(overrides:Record<number,string>={})=>values.flatMap((value,index)=>[flags[index]!,overrides[index]??value]);
const fs=(change:Partial<{realpath:string;kind:'file'|'directory'|'other';size:number;mode:number;data:string}>={})=>({realpath:()=>change.realpath??'/x/ollama',stat:()=>({kind:change.kind??'file',sizeBytes:change.size??1,mode:change.mode??0o755}),*readChunks(){yield Buffer.from(change.data??'x');}} as never);
const projection=(status:'PASS'|'FAIL'|'BLOCKED'='PASS')=>({contractVersion:PROVIDER_GENERATION_VALIDATION_CONTRACT_VERSION,status,failureCode:status==='PASS'?null:'EXPECTED_OUTPUT_MISMATCH' as const,promptDigest:VALIDATION_PROMPT_DIGEST,selectedProviderId:'ollama-cli:llama3.1:8b',selectedAdapterId:'ollama-cli',selectedModelId:'llama3.1:8b',planAttemptCount:1 as const,providerExecutionCount:1,retryCount:0,fallbackCount:0 as const,escalationCount:0 as const,normalizedOutput:status==='PASS'?'QUIRKYBOT_STAGE_2B_PROVIDER_OK':null,normalizedOutputDigest:'d',normalizedOutputBytes:31,expectedOutputMatched:status==='PASS',modelAcquisitionControl:ModelAcquisitionControl.PRECHECK_OBSERVE_POSTCHECK_RISK_ACCEPTED,modelDownloadPreventionVerified:false,downloadCapableCommandInvoked:true,downloadObserved:false,preflightPassed:true,postflightPassed:true,inventoryUnchanged:true,timedOut:false,outputOverflowed:false,externalEgressControl:ExternalEgressControl.CONFIG_RESTRICTED_RISK_ACCEPTED,externalEgressIsolationVerified:false,networkClass:'LOOPBACK_DAEMON' as const,checks:[]});
describe('strict parser',()=>{
  it('accepts exact input',()=>expect(parseProviderGenerationExecutionInvocation(invocation()).expectedExecutableSizeBytes).toBe(1));
  it.each([
    ['missing',invocation().slice(2)],['duplicate',[...invocation(),...invocation().slice(0,2)]],['unknown',['--unknown','x',...invocation()]],['positional',[...invocation(),'x']],
    ['relative',invocation({0:'ollama'})],['bad hash',invocation({1:'x'})],['uppercase hash',invocation({1:hash.toUpperCase()})],['bad size',invocation({2:'1.2'})],['negative',invocation({2:'-1'})],['zero',invocation({2:'0'})],['overflow',invocation({2:String(Number.MAX_SAFE_INTEGER+1)})],['max',invocation({2:String(MAX_EXECUTABLE_BYTES+1)})],
    ...['localhost','http://localhost:11434','http://[::1]:11434','http://10.0.0.1:11434','https://127.0.0.1:11434','http://127.0.0.1','http://127.0.0.1:0','http://127.0.0.1:65536','http://127.0.0.1:11434/x','http://127.0.0.1:11434?q=1','http://u:p@127.0.0.1:11434'].map((v)=>[`endpoint ${v}`,invocation({3:v})] as const),
    ['acquisition',invocation({4:'UNKNOWN'})],['egress',invocation({5:'UNKNOWN'})],
  ])('rejects %s',(_label,args)=>expect(()=>parseProviderGenerationExecutionInvocation(args)).toThrow());
});
describe('identity and lifecycle',()=>{
  it('reports invalid invocation once without disclosing rejected input',async()=>{const harness=vi.fn();const preflight=vi.fn();const writer=vi.fn();const rejected=['--remote-endpoint','http://remote.invalid:9999','oversized-secret','arbitrary-positional'];const r=await executeProviderGenerationExecution(rejected,{fileSystem:fs(),executeHarness:harness,runPreflight:preflight,writeProjection:writer});expect(r.exitCode).toBe(4);expect(r.projection).toMatchObject({status:'BLOCKED',failureCode:'INVALID_INVOCATION',harnessInvocationCount:0,identityVerified:false});expect(r.lifecycle).toMatchObject({projectionEmissionAttemptCount:1,projectionEmissionSucceeded:true});expect(writer).toHaveBeenCalledOnce();expect(harness).not.toHaveBeenCalled();expect(preflight).not.toHaveBeenCalled();expect(Object.keys(r.projection).sort()).toEqual([...PROVIDER_GENERATION_EXECUTION_PROJECTION_KEYS].sort());const serialized=JSON.stringify(r.projection);for(const value of rejected)expect(serialized).not.toContain(value);});
  it.each([['realpath',{realpath:'/other'}],['size',{size:2}],['sha',{data:'y'}],['directory',{kind:'directory' as const}],['mode',{mode:0}],['throw',null]])('blocks %s before harness',async(_label,change)=>{const harness=vi.fn();const fileSystem=change===null?({realpath:()=>{throw new Error('secret');}} as never):fs(change);const r=await executeProviderGenerationExecution(invocation(),{fileSystem,executeHarness:harness,writeProjection:vi.fn()});expect(r.exitCode).toBe(3);expect(harness).not.toHaveBeenCalled();expect(r.projection.identityVerified).toBe(false);});
  it.each([['PASS',0],['FAIL',2],['BLOCKED',3]] as const)('maps %s and exact keys',async(status,code)=>{const phases:string[]=[];const harness=vi.fn(async(_input,deps)=>{await deps.runPreflight('PRE');await deps.runPreflight('POST');return projection(status);});const r=await executeProviderGenerationExecution(invocation(),{fileSystem:fs(),executeHarness:harness,runPreflight:async phase=>{phases.push(phase);return {passed:true,requiredModelPresent:true,inventoryFingerprint:'f',externalEgressControl:ExternalEgressControl.CONFIG_RESTRICTED_RISK_ACCEPTED,externalEgressIsolationVerified:false,networkClass:'LOOPBACK_DAEMON'};},writeProjection:vi.fn()});expect(r.exitCode).toBe(code);expect(harness).toHaveBeenCalledOnce();expect(phases).toEqual(['PRE','POST']);expect(Object.keys(r.projection).sort()).toEqual([...PROVIDER_GENERATION_EXECUTION_PROJECTION_KEYS].sort());});
  it('preserves invocation and identity when harness throws',async()=>{const r=await executeProviderGenerationExecution(invocation(),{fileSystem:fs(),executeHarness:async()=>{throw new Error('/secret');},writeProjection:vi.fn()});expect(r.exitCode).toBe(5);expect(r.projection).toMatchObject({identityVerified:true,harnessInvocationCount:1});expect(JSON.stringify(r.projection)).not.toContain('/secret');});
});
describe('single writer attempt',()=>{
  it.each([['invalid',invocation().slice(2),undefined],['identity',invocation(),async()=>projection()],['pass',invocation(),async()=>projection('PASS')],['fail',invocation(),async()=>projection('FAIL')],['blocked',invocation(),async()=>projection('BLOCKED')],['unexpected',invocation(),async()=>{throw new Error('x');}]])('%s writer failure',async(_label,args,harness)=>{const writer=vi.fn(()=>{throw new Error('writer');});const r=await executeProviderGenerationExecution(args,{fileSystem:_label==='identity'?fs({data:'y'}):fs(),executeHarness:harness as never,writeProjection:writer});expect(r.exitCode).toBe(5);expect(writer).toHaveBeenCalledOnce();expect(r.lifecycle).toMatchObject({projectionEmissionAttemptCount:1,projectionEmissionSucceeded:false});});
  it('preserves received harness facts after writer failure',async()=>{const r=await executeProviderGenerationExecution(invocation(),{fileSystem:fs(),executeHarness:async()=>projection('PASS'),writeProjection:()=>{throw new Error('writer');}});expect(r.projection).toMatchObject({identityVerified:true,harnessInvocationCount:1,providerExecutionCount:1,downloadCapableCommandInvoked:true,preflightPassed:true,postflightPassed:true,inventoryUnchanged:true});expect(Object.keys(r.projection).sort()).toEqual([...PROVIDER_GENERATION_EXECUTION_PROJECTION_KEYS].sort());});
});
it('has no runtime, Provider, or Gateway wiring',()=>{const source=readFileSync(resolve(__dirname,'provider-generation-execution.ts'),'utf8');expect(source).not.toMatch(/OllamaCliProvider|ProviderRoutingGateway/);const app=readFileSync(resolve(__dirname,'../app.module.ts'),'utf8');expect(app).not.toContain('provider-generation-execution');});
